version: '3'

networks:
  kafka-spark-network:
    external: true

services:
  airflow-webserver:
    platform: linux/amd64
    image: apache/airflow:2.8.1-python3.10
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow:/opt/airflow
      - ./:/opt/project
    ports:
      - "8085:8080"
    command: webserver
    depends_on:
      - airflow-init
    networks:
      - kafka-spark-network

  airflow-scheduler:
    platform: linux/amd64
    image: apache/airflow:2.8.1-python3.10
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - ./airflow:/opt/airflow
      - ./:/opt/project
    command: scheduler
    depends_on:
      - airflow-init
    networks:
      - kafka-spark-network

  airflow-init:
    platform: linux/amd64
    image: apache/airflow:2.8.1-python3.10
    volumes:
      - ./airflow:/opt/airflow
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create --username admin --password admin \
          --firstname Mingan --lastname Choi --role Admin --email admin@example.com
    networks:
      - kafka-spark-network